---
- name: Rename index
  hosts: web
  become: yes 
  
  tasks:
  - name: Replace Hello World
    lineinfile:
      path: /var/www/html/index.nginx-debian.html
      regexp: 'Welcome to nginx!'
      line: '<p><script> document.write(new Date().toLocaleDateString()); </script></p>'
      owner: root
      group: root
      mode: '0644'

  - name: Ensure nginx service is started
    service:
      name: nginx
      state: started
 
